name: Pylint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pylint:
    runs-on: ubuntu-latest  # Określa system operacyjny, na którym workflow ma działać

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Pobiera kod z repozytorium

    - name: Set up Python
      uses: actions/setup-python@v2  # Ustawia wersję Pythona
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Uaktualnia pip
        pip install -r requirements.txt  # Instaluje zależności z pliku requirements.txt

    - name: Run pylint
      run: pylint app.py  # Uruchamia Pylinta na pliku app.py

    - name: Upload pylint results as artifact
      uses: actions/upload-artifact@v3
      with:
        name: pylint-report
        path: pylint_report.txt  # Opcjonalnie, możesz zapisać wyniki